title: 나의 세계관 기록소
locale: "ko-KR"
description: "기록과 기억의 저장소"
url: "https://mindud49.github.io" # 본인 주소 입력

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark" # air, contrast, mint, sunrise 등으로 변경 가능

# 플러그인 (필수)
plugins:
  - jekyll-include-cache
